#!/usr/bin/env bash
# Bash script that displays a list of currently running processes.
# Shows all processes, for all users, including those which might not have a TTY
# Displays them in a user-oriented format
# Shows process hierarchy
ps -auxf
