#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# But on the 4th iteration it prints bad luck
# Also on the 8th it prints good luck

x=1

while [ $x -le 10 ]
do
	if [ $x -eq 4 ]
	then
		echo "bad luck"
	elif [ $x -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	x=$((x+1))
done
