#!/usr/bin/env bash
# This script is displaying numbers 1..20
# But displays 4 and then bad luck from China for the 4th loop iteration
# But displays 9 and then bad luck from Japan for the 9th loop iteration
# But displays 17 and then bad luck from Italy for the 17th loop iteration

x=1

while [ $x -le 20 ]
do
	echo "$x"
	case $x in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
		*)
			;;
	esac
	x=$((x+1))
done
