#!/usr/bin/env bash
# This script is displaying numbers 1..20
# But displays 4 and then bad luck from China for the 4th loop iteration
# But displays 9 and then bad luck from Japan for the 9th loop iteration
# But displays 17 and then bad luck from Italy for the 17th loop iteration

x=1

while [ $x -le 20 ]
do
	if [ $x -eq 4 ]
	then
		echo "bad luck from China"
	elif [ $x -eq 9 ]
	then
		echo "bad luck from Japan"
	elif [ $x -eq 17 ]
	then
		echo "bad luck from Italy"
	else
		echo "$x"
	fi
	x=$((x+1))
done
