#!/usr/bin/env bash
# Name of the private key
KEY_NAME="school"
# Number of bits for the key
KEY_BITS=4096
# Passphrase for the key
PASSPHRASE="betty"

# Generate the RSA key pair
ssh-keygen -t rsa -b $KEY_BITS -f $KEY_NAME -N $PASSPHRASE

